config/routes.rb
Rails.application.routes.draw do
 
  root to: 'home#index'
  
  resources :schools, :only => [:index]
  controller :schools do
      post '/show_school' => :show
      post '/show_school_public_key' => :public_key_by_email, as: :school_public_key_by_email
  end
  
  resources :teachers, :except => [:edit, :update, :destroy, :show]
  controller :teachers do
      post '/show_teacher' => :show
      post 'give_teacher_public_key' => :public_key, as: :teacher_public_key
      post '/show_teacher_public_key' => :public_key_by_email, as: :teacher_public_key_by_email
  end
  
  resources :students, :except => [:edit, :update, :destroy, :show]
  controller :students do
      post '/show_student' => :show
      post '/show_student_public_key' => :public_key_by_email, as: :student_public_key_by_email
      post 'give_student_public_key' => :public_key, as: :student_public_key
    end
  
  controller :login_token do
      post '/send_login_token' => :give_login_token
      get '/login_token/:type/:id/:token' => :check_login_token, as: :check_login_token
    end
  
  controller :give_numbers do
      post '/give_numbers' => :give_numbers
  end

  
  controller :communicate do
      post '/communicate' => :index
  end
  
  controller :student_session do
      get    '/studentlogin' =>  :new
      post   '/studentlogin' => :create
      get '/studentlogout' =>  :destroy
      
  end
 
 controller :verify_and_reject do
     
     post '/signed' => :signed
     
end
 
 controller :posts do
     post '/my_posts_student' => :show, as: :post_show
     post '/post/new' =>  :new, as: :post_new
     post '/give_subcat_posts' => :give_subcategory, as: :give_subcat
     post '/give_previous_posts' => :give_previous, as: :give_previous
     post '/give_categories' => :give_categories, as: :give_categories
     post '/give_previous_posts_bysub' => :give_previous_bysub, as: :give_previous_bysub
     
 end
 resources :posts, :only => [:create]

 controller :teacher_posts do
     post '/my_posts_teacher' => :show, as: :teacher_post_show
     post '/teacher_post/new' =>  :new, as: :teacher_post_new
     post '/give_subcat_teacher_posts' => :give_subcategory, as: :give_teacher_subcat
     post '/give_teacher_posts_bysub' => :give_previous_bysub, as: :give_previous_teacher_bysub
 end
 resources :teacher_posts, :only => [:create]
 
 controller :teacher_session do
      get    '/teacherlogin' => :new
      post   '/teacherlogin' => :create
      get '/teacherlogout' => :destroy
    
  end
  
  
  controller :school_session do
      get    '/schoollogin' => :new
      post   '/schoollogin' => :create
      get '/schoollogout' => :destroy
    
  end
  
  controller :teacher_view_student_posts do
    
    post '/give_post_data' => :give_post_data, as: :give_post_data
    post '/give_student_data' => :give_student_data, as: :give_student_data
    post '/show_student_posts_teacher' => :show, as: :show_student_posts
    end
  
  controller :school_view_student_posts do
      
      post '/show_student_posts_school' => :show, as: :show_s_to_s_posts
  end
  
  controller :school_view_teacher_posts do
      post '/give_teacher_data' => :give_teacher_data, as: :give_teacher_data
      post '/give_teacher_post_data' => :give_teacher_post_data, as: :give_teacher_post_data
      post '/show_teacher_posts' => :show, as: :show_teacher_posts
    end

end

app/models/a_type.rb
class AType < ApplicationRecord
end

app/models/activity.rb
class Activity < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/family.rb
class Family < ApplicationRecord
end

app/models/parent1.rb
class Parent1 < ApplicationRecord
end

app/models/parent2.rb
class Parent2 < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/school.rb
class School < ApplicationRecord
  
  def send_token
      generate_token(:token)
      self.timestamp = Time.zone.now
      save!
      UserMailer.give_login_token(self, 3).deliver
  end
  def generate_token(column)
      begin
          self[column] = SecureRandom.urlsafe_base64
      end while School.exists?(column => self[column])
  end
  
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  def send_token
      generate_token(:token)
      self.timestamp = Time.zone.now
      save!
      UserMailer.give_login_token(self, 1).deliver
  end
  def generate_token(column)
      begin
          self[column] = SecureRandom.urlsafe_base64
      end while Student.exists?(column => self[column])
  end
end

app/models/t_type.rb
class TType < ApplicationRecord
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  
  def send_token
      generate_token(:token)
      self.timestamp = Time.zone.now
      save!
      UserMailer.give_login_token(self, 2).deliver
  end
  def generate_token(column)
      begin
          self[column] = SecureRandom.urlsafe_base64
      end while Teacher.exists?(column => self[column])
  end
  
end

app/models/teacher_post.rb
class TeacherPost < ApplicationRecord
end

app/models/testing.rb
class Testing < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token
  
#  respond_to :html, :js

  # GET /teachers
  # GET /teachers.json
  def index
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
      @students = Student.where(school: @teacher.school)
  end

  def public_key
      render :json => Teacher.find(params[:id].to_i)
  end
  
  def public_key_by_email
      render :json => Teacher.find_by(email: params[:email]).keys
    end
  
  # GET /teachers/new
  def new
    @teacher = Teacher.new
    @school = School.all
  end


  # POST /teachers
  # POST /teachers.json
  def create
      teacher = Teacher.new()
      teacher.email = params[:email]
      teacher.firstname = params[:firstname]
      teacher.lastname = params[:lastname]
      teacher.school = params[:school]
      teacher.keys = params[:keys]
      stud = Student.where(email: teacher.email)
      teach = Teacher.where(email: teacher.email)
      sch = School.where(email: teacher.email)
      
      if stud.length == 0 and teach.length == 0 && sch.length == 0
          teacher.save
          redirect_to teachers_path
          
          else
          redirect_to teachers_path, notice: 'User Exists'
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>


<%= link_to 'New Teacher', new_teacher_path %> |
<%= link_to 'Login', teacherlogin_path %> |
<%= link_to 'Back', root_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

Firstname : <input type="text" id = "fname"><br><br>
Lastname : <input type="text" id = "lname"><br><br>
Email : <input type="text" id = "email"><br><br>
School :
<select id = "school">
		<option value = 0 disabled selected>Choose One</option>
		<% @school.each do |sch| %>
			<option value = "<%=sch.id%>"><%= sch.name %></option>
		<%end%>
	</select>

<br>

<button onclick = "signin()">Submit</button><br><br>
<%= link_to 'Back', teachers_path %>


<script>
	function signin()
	{
		var firstname = document.getElementById("fname").value;
		var lastname = document.getElementById("lname").value;
		var email = document.getElementById("email").value;
		var school = document.getElementById("school").value;
		if (!(firstname))
			alert ("Enter First Name");
		else if (!(lastname))
			alert ("Enter Last Name");
		else if (!(email))
			alert ("Enter Email");
		else if (school == 0)
			alert ("Choose one School");
		else
		{
			var key = cryptico.generateRSAKey(email + bigInt.randBetween("-1e100", "1e100").toString(10), 1024);
			alert("The Next Message will Display your Private Key. Please keep it safe otherwise you would not be able to log into the platform. There is no other way to recover the private key. Do not store it only on your computer. Make sure to keep backups.");
			alert("This is your Private Key: \n" + bigInt(key.d);
			var data = {firstname: firstname, lastname: lastname, email: email, school: school + "", keys: bigInt(key.n).toString()};
			$.ajax({
            		url: '/teachers',
            		type: 'POST',
					data: data,
					async: false,
					});
		}
	}
	
</script>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @teacher.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @teacher.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>School:</strong>
  <%= School.find(@teacher.school).name %>
</p>

<p>

<h3>My Students</h3>
<table>
<% @students.each do |s| %>
<tr><td><%= s.firstname %></td> <td><%= s.lastname %></td>
<% if TeacherPost.where(teacher_id: @teacher.id, category: 1, status: 3).length != 0 %>
<td><form method="post" action="/show_student_posts_teacher" class="inline">
  <input type="hidden" name="stud_id" value="<%=s.id%>">
  <input type="hidden" name="id" value="<%=@teacher.id%>">
  <button type="submit" name="submit" value="Show" class="link-button">View Posts</button>
</form></td>
<%end%>
</tr>

<% end %>
</table>
</p>

<form method="post" action="/my_posts_teacher" class="inline">
  <input type="hidden" name="id" value="<%=@teacher.id%>">
  <button type="submit" name="submit" value="View" class="link-button">My Posts</button>
</form>
<p onclick = "logout()"><%= link_to 'Log Out', teacherlogout_url %></p>

<script>
	function logout()
	{
		sessionStorage.clear();
	}
	
</script>